on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Compile and Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["aarch64-unknown-linux-gnu", "i686-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-musl", "loongarch64-unknown-linux-musl", "riscv64gc-unknown-linux-musl", "x86_64-unknown-linux-musl", "arm-unknown-linux-musleabi", "arm-unknown-linux-musleabihf", "armv5te-unknown-linux-musleabi", "armv7-unknown-linux-musleabi", "armv7-unknown-linux-musleabihf", "i586-unknown-linux-musl", "i686-unknown-linux-musl"]
        exclude:
          - target: armv5te-unknown-linux-musleabi # fails to compile zvariant-5.2.0
          - target: riscv64-unknown-linux-musl # https://github.com/cross-rs/cross/issues/1197
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross-compilation tools
        run:  cargo install cross --git https://github.com/cross-rs/cross
      - name: Build for target ${{ matrix.target }}
        run: cross build --release "--target=${{ matrix.target }}"
      - name: Rename build
        run: mv "target/${{ matrix.target }}/release/mpris-stats" "target/mpris-stats-${{ matrix.target }}"
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: target/mpris-stats-${{ matrix.target }}
