on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Build and publish as release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - name: Build
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: target/x86_64-unknown-linux-musl/release/waylrc
